
import type { Metadata } from "next";



import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./components/SIdebar";
import { Header } from "./components/Header";
import { QueryComponent } from "./components/QueryComponent/Query";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Sidebar />
        {/* container para o conteúdo */}
        <main className="lg:ml-[276px] pl-4">
          <Header />
       <QueryComponent >
        {children}
       </QueryComponent>
        </main>
      </body>
    </html>
  );
}
